#!/bin/bash

# Script para deployment en Clever Cloud

echo "🚀 Configurando variables de entorno para Clever Cloud..."

# Variables de entorno que debes configurar en Clever Cloud
echo "📋 Variables de entorno requeridas:"
echo ""
echo "DJANGO_SETTINGS_MODULE=qr_site.clever_cloud_settings"
echo "SECRET_KEY=tu-secret-key-muy-segura-aqui"
echo "POSTGRESQL_ADDON_HOST=bihckcsbxtpycru7fzc3-postgresql.services.clever-cloud.com"
echo "POSTGRESQL_ADDON_DB=bihckcsbxtpycru7fzc3"
echo "POSTGRESQL_ADDON_USER=uv24d06xzigvcazpqhub"
echo "POSTGRESQL_ADDON_PORT=5432"
echo "POSTGRESQL_ADDON_PASSWORD=XpZCCVNaceAKNvn0wK3GgdqTpK3A7o"
echo "POSTGRESQL_ADDON_URI=postgresql://uv24d06xzigvcazpqhub:XpZCCVNaceAKNvn0wK3GgdqTpK3A7o@bihckcsbxtpycru7fzc3-postgresql.services.clever-cloud.com:5432/bihckcsbxtpycru7fzc3"
echo ""

echo "🔧 Comandos para Clever Cloud CLI:"
echo ""
echo "# Instalar Clever Cloud CLI si no lo tienes:"
echo "npm install -g clever-tools"
echo ""
echo "# Login"
echo "clever login"
echo ""
echo "# Crear aplicación"
echo "clever create --type python qr-generator"
echo ""
echo "# Configurar variables de entorno"
echo "clever env set DJANGO_SETTINGS_MODULE qr_site.clever_cloud_settings"
echo "clever env set SECRET_KEY 'tu-secret-key-muy-segura-aqui'"
echo "clever env set POSTGRESQL_ADDON_HOST bihckcsbxtpycru7fzc3-postgresql.services.clever-cloud.com"
echo "clever env set POSTGRESQL_ADDON_DB bihckcsbxtpycru7fzc3"
echo "clever env set POSTGRESQL_ADDON_USER uv24d06xzigvcazpqhub"
echo "clever env set POSTGRESQL_ADDON_PORT 5432"
echo "clever env set POSTGRESQL_ADDON_PASSWORD XpZCCVNaceAKNvn0wK3GgdqTpK3A7o"
echo "clever env set POSTGRESQL_ADDON_URI 'postgresql://uv24d06xzigvcazpqhub:XpZCCVNaceAKNvn0wK3GgdqTpK3A7o@bihckcsbxtpycru7fzc3-postgresql.services.clever-cloud.com:5432/bihckcsbxtpycru7fzc3'"
echo ""
echo "# Deploy"
echo "clever deploy"
echo ""

echo "✅ Configuración lista para Clever Cloud!"
echo ""
echo "📍 Pasos siguientes:"
echo "1. Ejecuta los comandos de arriba"
echo "2. Tu API estará en: https://app-id.cleverapps.io"
echo "3. Actualiza la URL en GitHub Pages"
echo "4. ¡Disfruta tu aplicación híbrida! 🎉"
