databases:
  - name: qr-postgres
    databaseName: qr_db
    user: qr_user

services:
  - type: web
    name: qr-generator
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn qr_site.wsgi:application"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qr-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
