# Generated by Django 5.2.4 on 2025-08-04 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoqr',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='accesos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name='codigoqr',
            options={'ordering': ['-creado']},
        ),
    ]
