# Generated by Django 5.2.4 on 2025-08-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20250804_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoqr',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
